listener 19283 127.0.0.1
allow_anonymous false
password_file /home/ubuntu/smartlife-primary/deploy/mosquitto.passwd

persistence true
persistence_location /home/ubuntu/smartlife-primary/data/mosquitto/
autosave_interval 60

log_dest stdout
log_type error
log_type warning
log_type notice
